In [1]:
#a Импортируйте библиотеку NumPy
import numpy as np
a = np.array ([1,2,3])
print (a)

[1 2 3]


In [2]:
#b.Создайте массив из 10 нулей
import numpy as np
f=np.zeros(10)
print(f)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#c.Создать массив из 10 единиц
f=np.ones(10)
print(f)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
#d.Создать массив из 10 пятерок
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
#e.Создать массив из целых чисел от 10 до 50
d=np.arange(10,51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [7]:
#f.Создать массив из четных чисел от 10 до 50
k= np.arange(10,51,2)
print(k)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [8]:
#g.Создать матрицу 3х3 с числами от 0 до 8
z=np.arange(0,9)
z_2d = z.reshape(3, 3)
print(z_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#h.Создать единичную матрицу 3x3
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#i.Используйте NumPy для генерации случайного числа от 0 до 1
x=np.random.random(1)[0]
print(x)

0.9847260931027001


In [11]:
#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
i= np.random.rand(25)
print(i)

[0.24536928 0.12022672 0.02451725 0.90632669 0.06124586 0.08750904
 0.90230818 0.98010156 0.73256161 0.66629395 0.22761215 0.06204575
 0.95891226 0.44360721 0.39986914 0.93763748 0.60376758 0.6686735
 0.00377016 0.93888635 0.92449841 0.85294452 0.76467747 0.57901472
 0.43147598]


In [17]:
#k.Создайте следующую матрицу используя функции библиотеки NumPy
k=np.linspace(0.01,1.,100).reshape(10,10)
print(k)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [21]:
#I.Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!).
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('l =' , mat[2:, 1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
l = [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [22]:
#m.Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l
mat = np.arange(1,26).reshape(5,5)
ar = mat[mat==20]
print(ar)
     

[20]


In [23]:
#n.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
mat = np.arange(1,26).reshape(5,5)
print('j=',  mat[0:3,1].reshape(3,1))

j= [[ 2]
 [ 7]
 [12]]


In [24]:
#o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
arr=np.arange(1,26).reshape(5,5)
temp=arr[4,:]
print(temp)

[21 22 23 24 25]


In [30]:
#p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
mat=np.arange(1,26).reshape(5,5)
temp=mat[3:0,4:4]
print(temp)

[]


In [29]:
#q.Получить сумму всех значений в стартовой матрице mat
import numpy as np
mat=np.arange(1,26).reshape(5,5)
print(mat.sum())

325


In [28]:

#r.Получить стандартное отклонение в стартовой матрице mat
import numpy as np
mat=np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


In [33]:
#s.Получить сумму значений в колонках в стартовой матрице mat
import numpy as np
mat=np.arange(1,26).reshape(5,5)
t=mat[[0,1,2,3,4],0]
n=mat[[0,1,2,3,4],1]
q=mat[[0,1,2,3,4],2]
g=mat[[0,1,2,3,4],3]
l=mat[[0,1,2,3,4],4]
print(t.sum(), n.sum(), q.sum(), g.sum(), l.sum())

55 60 65 70 75
